---
title: "cartsev2"
output: html_document
date: "2023-04-20"
---

### CART sur la sévérité


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rpart)
library(rpart.plot)
library(sp)
library(CASdatasets)
library(party)
library(partykit)
```

```{r}
data(freMPL5)

#Prise en main des données

#enlever les valeurs négatives
freMPL5 <- subset(freMPL5, freMPL5$ClaimAmount >= 0)
#passer en variables catégorielles
freMPL5$HasKmLimit <- factor(freMPL5$HasKmLimit)
freMPL5$ClaimInd <- factor(freMPL5$ClaimInd)
#segmentation des tranches d'âge
freMPL5$DrivAge_fact <- cut(freMPL5$DrivAge, c(20,25,30,35,40,45,50,58,65,120), include.lowest = TRUE)
#Découpage CSP
freMPL5$Categ <-  ifelse(freMPL5$SocioCateg %in% c("CSP46","CSP48"), "Categ1",
ifelse(freMPL5$SocioCateg %in% c("CSP50","CSP55"), "Categ2",
ifelse(freMPL5$SocioCateg %in% c("CSP60"),"Categ3",
ifelse(freMPL5$SocioCateg %in% c("CSP42","CSP1", "CSP66"),"Categ4","Categ0"))))
freMPL5$Categ = factor(freMPL5$Categ)
#découpage RiskArea
freMPL5$RiskArea <- ifelse(freMPL5$RiskArea %in% c(1,2,3,12,13), "ZoneRisque1",
ifelse(freMPL5$RiskArea %in% c(5,6,7,8,9), "ZoneRisque2",
ifelse(freMPL5$RiskArea %in% c(10,11), "ZoneRisque3",
ifelse(freMPL5$RiskArea %in% c(4), "ZoneRisque4", NA))))
freMPL5$RiskArea <- factor(freMPL5$RiskArea)
```


```{r, error = TRUE}

#Prise en compte uniquement des données ayant au moins un sinistre

cout <- freMPL5[freMPL5$ClaimInd == 1,]
```

```{r}

#Séparation des données en échantillon d'entrainement et de test

set.seed(179)
perm <- sample(nrow(cout),80/100*nrow(cout))
trainCartSEV.data <- cout[perm,]
testCartSEV.data  <- cout[-perm,]
```




```{r}
#étape de construction de l'arbre maximal
freMPL5.Tree.Amount <- rpart(ClaimAmount~MariStat+Categ+VehUsage+HasKmLimit+ClaimNbResp+ClaimNbNonResp+ClaimNbParking+ClaimNbFireTheft+ClaimNbWindscreen+OutUseNb+RiskArea+BonusMalus+DrivAge_fact,
                      data=trainCartSEV.data,
                      control=rpart.control(xval = 20,minbucket = 1, maxdepth=8,cp=0))
#affichage de l'arbre maximal (pré-élagué)
rpart.plot(freMPL5.Tree.Amount)


```



```{r}
#On utilise plotcp pour afficher la courbe du taux d'erreur relatif en fonction des cp, on choisi un cp qui minimise ce taux d'erreur pour une taille correcte
plotcp(freMPL5.Tree.Amount)
printcp(freMPL5.Tree.Amount)
```

```{r}

#étape d'élagage de l'arbre avec un cp qui minimise le taux d'erreur relatif tout en donnant un arbre de taille correcte

freMPL5.Tree.prune.Amount=prune(freMPL5.Tree.Amount,cp= 1.4027e-02)
#affichage de l'arbre final
rpart.plot(freMPL5.Tree.prune.Amount)
```

```{r}

#mse pour le premier arbre pré-élagué

predic <- predict(freMPL5.Tree.Amount, newdata = testCartSEV.data)
mse1 <- mean((predic - testCartSEV.data$ClaimAmount)^2)
mse1

```

```{r}
#mse pour l'arbre final
pred <- predict(freMPL5.Tree.prune.Amount, newdata = testCartSEV.data)
mse <- mean((pred - testCartSEV.data$ClaimAmount)^2)
mse

```

```{r}
#rmse pour l'arbre final

rmse <- sqrt(mse)
rmse

```

```{r}
#mae pour l'arbre final
pred <- predict(freMPL5.Tree.prune.Amount, newdata = testCartSEV.data)
mae <- mean(abs(pred - testCartSEV.data$ClaimAmount))
mae

```


```{r}
#moyenne du montant des sinistres 
mean_pred <- mean(pred)
mean_pred
```

```{r}
#importance des variables dans l'arbre final
importance <- round(freMPL5.Tree.prune.Amount$variable.importance/sum(freMPL5.Tree.prune.Amount$variable.importance)*100, 2)
importance
```

```{r}
#affichage de la courbe de R2 en fonction du nombre de division
rsq.rpart(freMPL5.Tree.Amount)
```

```{r}
#nombre de noeuds dans le premier arbre
n_nodes <- nrow(freMPL5.Tree.Amount$frame)
cat("Nombre de noeuds dans l'arbre CART:", n_nodes, "\n")
```



```{r}

summary(freMPL5.Tree.prune.Amount)
```
