---
title: "GLMTREEAMOUNT"
output: html_document
date: "2023-04-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("party")
install.packages("partykit")
```

```{r}
library(rpart)
library(rpart.plot)
library(sp)
library(CASdatasets)
library(party)
library(partykit)
```

```{r}
#enlever les valeurs négatives
freMPL5 <- subset(freMPL5, freMPL5$ClaimAmount >= 0)

#passer en variables catégorielles
freMPL5$HasKmLimit <- factor(freMPL5$HasKmLimit)
freMPL5$ClaimInd <- factor(freMPL5$ClaimInd)

#segmentation des tranches d'âge
freMPL5$DrivAge_fact <- cut(freMPL5$DrivAge, c(20,25,30,35,40,45,50,58,65,120), include.lowest = TRUE)

#Découpage CSP
freMPL5$Categ <-  ifelse(freMPL5$SocioCateg %in% c("CSP46","CSP48"), "Categ1",
ifelse(freMPL5$SocioCateg %in% c("CSP50","CSP55"), "Categ2",
ifelse(freMPL5$SocioCateg %in% c("CSP60"),"Categ3",
ifelse(freMPL5$SocioCateg %in% c("CSP42","CSP1", "CSP66"),"Categ4","Categ0"))))
freMPL5$Categ = factor(freMPL5$Categ)

#découpage RiskArea
freMPL5$RiskArea <- ifelse(freMPL5$RiskArea %in% c(1,2,3,12,13), "ZoneRisque1",
ifelse(freMPL5$RiskArea %in% c(5,6,7,8,9), "ZoneRisque2",
ifelse(freMPL5$RiskArea %in% c(10,11), "ZoneRisque3",
ifelse(freMPL5$RiskArea %in% c(4), "ZoneRisque4", NA))))

freMPL5$RiskArea <- factor(freMPL5$RiskArea)
```

```{r, error = TRUE}
cout8 <- freMPL5[freMPL5$ClaimInd == 1,]
```

```{r}
cout3 <- subset(cout, cout$ClaimAmount <20000)
set.seed(123)
perm <- sample(nrow(cout3),80/100*nrow(cout3))
trainGLM.data <- cout3[perm,]
testGLM.data  <- cout3[-perm,]

```

```{r}


glm_tree_lognormale <- glmtree(log(ClaimAmount) ~ MariStat+Categ+VehUsage+HasKmLimit+ClaimNbResp+ClaimNbNonResp+ClaimNbParking+ClaimNbFireTheft+ClaimNbWindscreen+OutUseNb+RiskArea+BonusMalus+DrivAge_fact|MariStat+Categ+VehUsage+HasKmLimit+ClaimNbResp+ClaimNbNonResp+ClaimNbParking+ClaimNbFireTheft+ClaimNbWindscreen+OutUseNb+RiskArea+BonusMalus+DrivAge_fact,
  data = trainGLM.data, maxdepth = 5, family = gaussian(link = "identity"))
plot(glm_tree_lognormale)


```

```{r}
AIC(glm_tree_lognormale)
BIC(glm_tree_lognormale)
```

```{r}
predglmT <- predict(glm_tree_lognormale, newdata = testGLM.data)
mse <- mean((predglmT - testGLM.data$ClaimAmount)^2)
mse
```

```{r}
#moyenne du montant des sinistres
mean_pred <- mean(predglmT)
mean_pred
```

```{r}
glm_tree_gamma <- glmtree(ClaimAmount ~ MariStat+Categ+VehUsage+HasKmLimit+ClaimNbResp+ClaimNbNonResp+ClaimNbParking+ClaimNbFireTheft+ClaimNbWindscreen+OutUseNb+RiskArea+BonusMalus+DrivAge_fact|MariStat+Categ+VehUsage+HasKmLimit+ClaimNbResp+ClaimNbNonResp+ClaimNbParking+ClaimNbFireTheft+ClaimNbWindscreen+OutUseNb+RiskArea+BonusMalus+DrivAge_fact,
  data = train, maxdepth = 7, family = Gamma(link = "identity"))
plot(glm_tree_gamma)
```
