---
title: "Analyse_de_données_partie_2"
author: "Dudot Lucas - Lapaz Eudes - Moinard Benjamin - Nanoux Louis"
date: "2023-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import de packages utiles

```{r, message=FALSE}
library(FactoMineR)
library(factoextra)
library(CASdatasets)
library(tidyverse)
library(MASS)
library(knitr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(dplyr)
library(GGally)
library(corrplot)
library(carData) 
library(car)
library(questionr)
library(multcomp)
library(dplyr)
library(leaps)
library(TeachingDemos)
library(FactoMineR)
library(factoextra)
library(ROCR)
library(plotROC)
```

## Documentation et import du dataset

```{r}
#?CASdatasets #ouvre l'aide pour comprendre le dataset
data(freMPL5)
summary(freMPL5)
```

On remarque que certaines variables sont numériques au lieu d'être considérées comme des facteurs. Nous allons donc les changer :

```{r}
freMPL5$HasKmLimit <- factor(freMPL5$HasKmLimit)
freMPL5$ClaimInd <- factor(freMPL5$ClaimInd)
freMPL5$OutUseNb <- as.numeric(freMPL5$OutUseNb)
```

```{r}
A = kde2d(freMPL5$DrivAge, freMPL5$BonusMalus)
filled.contour(A)
A = kde2d(freMPL5$DrivAge, freMPL5$LicAge)
filled.contour(A)
A = kde2d(freMPL5$DrivAge, freMPL5$Exposure)
filled.contour(A)
A = kde2d(freMPL5$DrivAge, freMPL5$ClaimNbNonResp)
filled.contour(A)
A = kde2d(freMPL5$DrivAge, freMPL5$ClaimNbWindscreen)
filled.contour(A)
A = kde2d(freMPL5$DrivAge, freMPL5$RiskArea)
filled.contour(A)
```

```{r}
A = kde2d(freMPL5$BonusMalus, freMPL5$LicAge)
filled.contour(A)
A = kde2d(freMPL5$BonusMalus, freMPL5$Exposure)
filled.contour(A)
A = kde2d(freMPL5$BonusMalus, freMPL5$ClaimNbNonResp)
filled.contour(A)
A = kde2d(freMPL5$BonusMalus, freMPL5$ClaimNbWindscreen)
filled.contour(A)
A = kde2d(freMPL5$BonusMalus, freMPL5$RiskArea)
filled.contour(A)
```

```{r}
A = kde2d(freMPL5$LicAge, freMPL5$Exposure)
filled.contour(A)
A = kde2d(freMPL5$LicAge, freMPL5$ClaimNbNonResp)
filled.contour(A)
A = kde2d(freMPL5$LicAge, freMPL5$ClaimNbWindscreen)
filled.contour(A)
A = kde2d(freMPL5$LicAge, freMPL5$RiskArea)
filled.contour(A)
```

```{r}
A = kde2d(freMPL5$Exposure, freMPL5$ClaimNbNonResp)
filled.contour(A)
A = kde2d(freMPL5$Exposure, freMPL5$ClaimNbWindscreen)
filled.contour(A)
A = kde2d(freMPL5$Exposure, freMPL5$RiskArea)
filled.contour(A)
```

```{r}
A = kde2d(freMPL5$ClaimNbNonResp, freMPL5$ClaimNbWindscreen)
filled.contour(A)
A = kde2d(freMPL5$ClaimNbNonResp, freMPL5$RiskArea)
filled.contour(A)
```

```{r}
A = kde2d(freMPL5$ClaimNbWindscreen, freMPL5$RiskArea)
filled.contour(A)
```

On remarque donc uniquement une réelle forte corrélation entre LicAge et DrivAge pour les variables continues.

```{r}
#freMPL veut dire French Motor Personal Line datasets
#On utilisera le dataset 5 qui contient environ 26000 contrats de l'annee 2004

x <- freMPL5[, c(1,2,9,11,12,13,14,15,16,17,18,19)]
corrplot(round(cor(x),2),method="ellipse")

#C'est une ACP sur les données quantitatives (on a ici considéré la zone
#comme faisant partie des variables quantitatives car c'est "possibly ordered")
PCA(x)
```

```{r}
#On veut ici supprimer les lignes dont les montants réclamés sont négatifs.
#En effet, elles donnent lieu à une régularisation et ne nous apporterons rien.
data(freMPL5)
freMPL5 <- subset(freMPL5, freMPL5$ClaimAmount >= 0)
freMPL5$HasKmLimit <- factor(freMPL5$HasKmLimit)
freMPL5$RiskArea <- factor(freMPL5$RiskArea)
freMPL5$ClaimInd <- factor(freMPL5$ClaimInd)
freMPL5$ClaimNbFireTheft <- factor(freMPL5$ClaimNbFireTheft)
freMPL5$ClaimNbResp <- factor(freMPL5$ClaimNbResp)
freMPL5$ClaimNbNonResp <- factor(freMPL5$ClaimNbNonResp)
freMPL5$ClaimNbParking <- factor(freMPL5$ClaimNbParking)
freMPL5$ClaimNbWindscreen <- factor(freMPL5$ClaimNbWindscreen)
freMPL5$ClaimInd <- factor(freMPL5$ClaimInd)
freMPL5$OutUseNb <- factor(freMPL5$OutUseNb)


#Pour faire une analyse de données, nous allons transformer toutes les variables
#quantitatives en variables qualitatives de manière à avoir un nombre homogènes
#d'assurés dans chaque classe.
freMPL5$Exposure <- cut(freMPL5$Exposure, quantile(freMPL5$Exposure, probs = seq(0,1,1/4)), include.lowest = TRUE)
freMPL5$DrivAge <- cut(freMPL5$DrivAge, quantile(freMPL5$DrivAge, probs = seq(0,1,1/6)), include.lowest = TRUE)
freMPL5$LicAge <- cut(freMPL5$LicAge, quantile(freMPL5$LicAge, probs = seq(0,1,1/6)), include.lowest = TRUE)
freMPL5$BonusMalus <- cut(freMPL5$BonusMalus, c(50,54,seq(60, 200, 20)), include.lowest = TRUE)
freMPL5$IntervalCout <- cut(freMPL5$ClaimAmount, c(0,seq(1, 100000, 1000)), include.lowest = TRUE)
```

```{r}
fact <- select(freMPL5, !c(RecordBeg, RecordEnd, ClaimAmount))

res.mca = MCA(fact, ncp = 5, graph = TRUE)
summary(res.mca)
fviz_mca_var(res.mca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE, 
             ggtheme = theme_minimal())
mca.graph(res.mca, choix = "var", axes = 1)
```

```{r}

#Un premier modèle linéaire généralisé de loi gamma
data_cout = select(freMPL5[freMPL5$ClaimInd == 1, ], -c("ClaimInd", "IntervalCout","Freq","RecordBeg", "RecordEnd"))
summary(data_cout)
mod0 <- glm(ClaimAmount~LicAge , data = data_cout, family=Gamma(link="inverse"))
summary(mod0)

#Etude des résidus de Pearson et de Deviance
residus.P = residuals(mod0, type="pearson")
residus.D = residuals(mod0, type="deviance")
```
